app/employee/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileRequired, FileField
from wtforms import StringField, SubmitField, DateField
from wtforms.validators import DataRequired


class AddEmployee(FlaskForm):
    last_name = StringField('Фамилия', validators=[DataRequired()])
    first_name = StringField('Имя', validators=[DataRequired()])
    patronymic_name = StringField('Отчество')
    birth_date = DateField('Дата рождения', format='%d-%m-%Y')
    position = StringField('Должность', validators=[DataRequired()])
    photo = FileField('Фотография')
    phone_number = StringField('Номер телефона', validators=[DataRequired()])
    submit = SubmitField('Добавить')


class EditEmployee(FlaskForm):
    last_name = StringField('Фамилия', validators=[DataRequired()])
    first_name = StringField('Имя', validators=[DataRequired()])
    patronymic_name = StringField('Отчество')
    birth_date = DateField('Дата рождения', format='%d-%m-%Y')
    position = StringField('Должность', validators=[DataRequired()])
    photo = FileField('Фотография')
    phone_number = StringField('Номер телефона', validators=[DataRequired()])
    submit = SubmitField('Изменить')

app/employee/__init__.py
from flask import Blueprint
bp = Blueprint('employee', __name__)
from app.employee import routes

app/employee/routes.py
from flask import render_template, flash, redirect, url_for, request, g
from flask_login import current_user, login_required
from app import db
from app.employee.forms import AddEmployee, EditEmployee
from app.models import Employee
from app.employee import bp
from app import photos


@bp.route('/employees')
@login_required
def employees():
    technicians = Employee.query.all()
    return render_template('employee/employees.html', title='Сотрудники', employees=True, technicians=technicians)


@bp.route('/employees/add_employee', methods=['POST', 'GET'])
@login_required
def add_employee():
    add_form = AddEmployee()
    if add_form.validate_on_submit():
        query = Employee(first_name=add_form.first_name.data, last_name=add_form.last_name.data,
                         patronymic_name=add_form.patronymic_name.data, position=add_form.position.data,
                         birth_date=add_form.birth_date.data, photo=add_form.photo.data,
                         phone_number=add_form.phone_number.data)
        db.session.add(query)
        db.session.commit()
        return redirect(url_for('employee.employees'))
    return render_template('employee/add_employee.html', title='Создание профиля сотрудника', add_employee=True,
                           add_form=add_form)


@bp.route('/employees/id<int:id>', methods=['GET', 'POST'])
@login_required
def employee_profile(id):
    profile_data = Employee.query.filter(Employee.id == id).first_or_404()
    edit_form = EditEmployee()
    if edit_form.validate_on_submit():
        query = Employee.query.filter(Employee.id == id).first_or_404()
        query.first_name = edit_form.first_name.data
        query.last_name = edit_form.last_name.data
        query.patronymic_name = edit_form.patronymic_name.data
        query.birth_date = edit_form.birth_date.data
        query.phone_number = edit_form.phone_number.data
        query.position = edit_form.position.data

        if edit_form.photo.data:
            filename = 'uploads/' + photos.save(edit_form.photo.data)
            query.photo = filename

        db.session.commit()
        flash('Ваши изменения сохранены')
        return redirect(url_for('employee.employee_profile', id=id))

    elif request.method == 'GET':
        query = Employee.query.filter(Employee.id == id).first_or_404()
        edit_form.first_name.data = query.first_name
        edit_form.last_name.data = query.last_name
        edit_form.patronymic_name.data = query.patronymic_name
        edit_form.phone_number.data = query.phone_number
        edit_form.birth_date.data = query.birth_date
        edit_form.position.data = query.position
    return render_template('employee/employee_profile.html', title=profile_data.last_name + ' ' +
                                                                   profile_data.first_name[:1] + '. ' +
                                                                   profile_data.patronymic_name[:1] + '.',
                           profile_data=profile_data, employees=True, edit_form=edit_form)

app/templates/employee/add_employee.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content %}

{% if add_form %}
<div class="col-lg-4">
    {{ wtf.quick_form(add_form) }}
</div>
{% endif %}

{% endblock %}

app/templates/employee/employee_profile.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url_for('main.index')}}">Главная</a></li>
        <li class="breadcrumb-item"><a href="{{ url_for('employee.employees')}}">Сотрудники</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ profile_data.last_name + ' ' + profile_data.first_name[:1] +'. ' + profile_data.patronymic_name[:1] + '.'}}</li>
    </ol>
</nav>
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h3 class="h2">Карточка сотрудника</h3>
    </div>
    <div class="row">
        <div class="col-lg-3">
            <img class="img-thumbnail rounded" src="{%if profile_data.photo%}
            {{ url_for ('static', filename=profile_data.photo) }}
            {% else %}
              {{ url_for ('static', filename='uploads/profile/nobody.jpg') }}
             {% endif %}">
        </div>
        <div class="col-lg-8">
            <nav>
                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Профиль</a>
                    <a class="nav-item nav-link" id="nav-docs-tab" data-toggle="tab" href="#nav-docs" role="tab" aria-controls="nav-documentation" aria-selected="false">Документы</a>
                    <a class="nav-item nav-link" id="nav-edit-tab" data-toggle="tab" href="#nav-edit" role="tab" aria-controls="nav-maintenance" aria-selected="false">Редактировать карточку</a>
                </div>
            </nav>
            <div class="tab-content py-3" id="nav-tabContent">
                <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                    <div class="row">
                        <div class="col-sm-5" >Фамилия:</div><div class="col-sm-7">{{ profile_data.last_name }}</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5" >Имя:</div><div class="col-sm-7">{{ profile_data.first_name }}</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5 ">Отчество:</div><div class="col-sm-7">{{ profile_data.patronymic_name }}</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5" >Дата рождения:</div><div class="col-sm-7">{{ profile_data.birth_date }}</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5" >Должность:</div><div class="col-sm-7">{{ profile_data.position }}</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5" >Номер телефона:</div><div class="col-sm-7">{{ profile_data.phone_number }}</div>
                    </div>
                </div>

                <div class="tab-pane fade" id="nav-docs" role="tabpanel" aria-labelledby="nav-docs-tab">
                    не реализовано
                </div>
                <div class="tab-pane fade" id="nav-edit" role="tabpanel" aria-labelledby="nav-edit-tab">
                    {{ wtf.quick_form(edit_form) }}
                </div>
            </div>
        </div>
    </div>


{% endblock %}

app/templates/employee/employees.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url_for('main.index')}}">Главная</a></li>
        <li class="breadcrumb-item active" aria-current="page">Сотрудники</li>
    </ol>
</nav>
{% if technicians %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom py-1">
    <h2 class="h2">Список сотрудников вашего участка</h2>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a class="btn btn-sm btn-outline-secondary" href="{{ url_for('employee.add_employee')}}">Добавить сотрудника</a>
    </div>
</div>
<div class="col-lg-6">
    <ul class="list-group">
        {% for i in technicians %}
        <li class="list-group-item"><a href="{{url_for('employee.employee_profile', id=i.id) }}">{{ i.last_name + ' ' + i.first_name + ' ' + i.patronymic_name}}</a></li>

        {% endfor %}
    </ul>
</div>

{% else %}
<div class="row">
    Вы не создали ни одного профиля сотрудника.
    Нажмите <a href="{{ url_for('employee.add_employee')}}"> сюды</a>, чтобы исправить это.
</div>
{% endif %}

{% endblock %}